refresh_rate: 30 seconds
appenders:
  app_stdout:
    kind: console
  app_log_file:
    kind: rolling_file
    path: "log/app.log"
    policy:
      trigger:
        kind: size
        limit: 10kb
      roller:
        kind: fixed_window
        base: 1
        count: 9
        pattern: "log/app{}.log"
root:
  level: debug
  appenders:
    - app_stdout
loggers:
  log_file:
    level: info
    appenders:
      - app_log_file
    additive: false